### ISSUE TITLE
Question Entity + Service + Route

### ISSUE THREAD

**Issue by SimOneGollo** [RIP-Comm/AMAlanche#14]
It is necessary to integrate a question entity with the following fields:

- id
- text
- upvotes
- owner  --> need user FK 
- session --> need session FK 
- isPinned
- createdAt

This issue expects that the creation of QuestionService with basic CRUD operation on Question entity and some route to test it.

- [ ] Question Entity
- [ ] Question Service
- [ ] Question route (get, post, put, delete)

**Comment by bozzelliandrea** [comment]
@SimOneGollo i'll take this issue, but i have a question, where i can find the session FK? i saw that there is only the user entity.

**Comment by SimOneGollo** [comment]
> @SimOneGollo i'll take this issue, but i have a question, where i can find the session FK? i saw that there is only the user entity.

I didn't have time add same issue for the session. I'm creating it now.
