### ISSUE TITLE
To implement errors middleware

### ISSUE THREAD

**Issue by datge** [RIP-Comm/AMAlanche#3]

**Comment by SimOneGollo** [comment]
What do you mean with "errors meddleware"? Which errors do you want handle?

**Comment by datge** [comment]
This, i have seen you added in https://github.com/RIP-Comm/AMAlanche/pull/6
```typescript
  app.use((err, req: Request, res: Response, next) => {
    if(isCelebrateError(err)){
      const error = {
        details: err.details,
        message: err.message,
        name: err.name,
        stack: err.stack
      }
      res.status(400).json(error);
    } else {
      next(err);
    }
  })
```

**Comment by SimOneGollo** [comment]
Yes, because reading the celebrate documentation i expected that it return 400 error by default but this is not true. I noted it while i was testing Users routes and fix it.
