### ISSUE TITLE
To add linter and conventional commits hook

### ISSUE THREAD

**Issue by datge** [RIP-Comm/AMAlanche#4]

**Comment by matteasu** [comment]
@datge for eslint what configuration should we choose? Do we want to enforce code style ?

**Comment by datge** [comment]
In my opinion, something like that `{
  "parser": "@typescript-eslint/parser",
  "env": {
    "node": true
  },
  "plugins": ["prettier"],
  "extends": ["eslint:recommended", "prettier"],
  "parserOptions": { "ecmaVersion": 2020, "sourceType": "module" },
  "rules": {
    "prettier/prettier": "error",
    "no-console": "error"
  },
  "overrides": [
    {
      "files": ["*.ts", ".tsx"],
      "plugins": ["@typescript-eslint"],
      "extends": ["plugin:@typescript-eslint/recommended"],
      "rules": {
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-unused-vars": [
          "error",
          {
            "varsIgnorePattern": "^_",
            "argsIgnorePattern": "^_"
          }
        ]
      }
    }
  ]
}
`
With prettier, otherwise we are going to replace each other style, and i think is even better for typescript beginners to force them on good practices at disvantage of 'any'.

**Comment by matteasu** [comment]
Ok, I'll work on this later today

**Comment by matteasu** [comment]
@datge can you check ? Also Sorry for committing directly to the main branch, I have to fix my git client to send commits to my fork rather than the main repo

**Comment by SimOneGollo** [comment]
@matteasu, when I try to launch the command `npm run lint:check`, npm say me to install eslint-plugin-prettier. Can you fix it?

**Comment by datge** [comment]
yes i think miss the eslint-plugin-prettier used by esling, i can add it
